replicaCount: 2

image:
  repository: jumma786/mlops-prediction-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

monitoring:
  enabled: true
  prometheus: true
  grafana: true

probes:
  liveness:
    path: /health/live
    initialDelaySeconds: 10
    periodSeconds: 30
  readiness:
    path: /health/ready
    initialDelaySeconds: 5
    periodSeconds: 10
