apiVersion: v1
kind: Namespace
metadata:
  name: mlops
  labels:
    name: mlops
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: mlops
data:
  ARTIFACTS_DIR: /app/artifacts
  MODEL_VERSION: "1.0.0"
  LOG_LEVEL: INFO
