apiVersion: v1
kind: Service
metadata:
  name: mlops-prediction-api
  namespace: mlops
  labels:
    app: mlops-prediction-api
spec:
  selector:
    app: mlops-prediction-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
